package mongoConnection;

import org.bson.Document;
import org.bson.types.ObjectId;

import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;

public class Connection {
	
	public static void main(String[] args) {
		// create connection string to connect to cloud mongo with user/password
		// generated by security/database access
		// watch out the IP, pal!
		// string connection from Atlas/Connect
		MongoClientURI connectionString = new MongoClientURI("mongodb+srv://CJC80Storm:Kilo1234@cluster0.cfn7d.mongodb.net/test");//mongodb+srv://CJC80Storm:<password>@cluster0.cfn7d.mongodb.net/test
		// create object mongoClient: object to connect, manage, get DBs, handle, ...
		// CRUD, clean, etc ...
		MongoClient mongoClient = new MongoClient(connectionString);

		// getter from mongo to get db, particularly CITY
		MongoDatabase database = mongoClient.getDatabase("birds");//city
		// collection CARS
		MongoCollection<Document> collection = database.getCollection("bird");//cars

		System.out.println("Number of birds in my Bird collection: "+collection.countDocuments());

		// query to my collection and find the first document and then transform to JSON
		// in order to print that document as JSON and STRING
		Document myDoc = collection.find().first();
		System.out.println(myDoc.toJson());
		System.out.println(myDoc.toString());

		// create a new Car as a DOCUMENT
		Document bird = new Document("_id", new ObjectId());
		// set the document with APPEND
		bird.append("make", "Magda").append("price", 5000d).append("designeBy", "Martinelli, Sonia");
		// add that document to CARS collection
		collection.insertOne(bird);
		
		System.out.println("New document, new Bird: " + collection.countDocuments());

		// print all documents from my collection Birds
		for (Document birdToPrint : collection.find()) {
			System.out.println(birdToPrint.toJson());
		}

	}

}
